name: setup-node

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3.0.0
    - uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile
      shell: bash
