name: setup-node

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4.2.0

    - uses: actions/setup-node@v4.1.0
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'

    - run: pnpm i --frozen-lockfile
      shell: bash
