name: Lint Commit Messages

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v6
